### ISSUE TITLE
博主你好，在尝试复现该程序的是否遇到问题给我造成较长事件的困扰希望得到你的帮助。

### ISSUE THREAD

**Issue by jimisun123** [wf0/CSDN#1]
我在尝试复现此程序时候，操作步骤是这样的。

1. 安装     
```
"vue-socket.io": "^3.0.10",
```

2. 配置
```js
Vue.use(Vant,
    new VueSocketIO({
        debug: false, // debug调试，生产建议关闭
        connection: "http://localhost:9999",
        vuex: {
            store,
            actionPrefix: 'SOCKET_',
            mutationPrefix: 'SOCKET_'
        },
        options: {     //Optional options,
            autoConnect: false,       // 自动连接     这里为我项目需求  需要在指定情况下才连接socket
            path: "/ws",
            transports: ['websocket']
        }
    })
)
```

3. 尝试在组件中发送事件
```js
 this.$socket.emit("hell","hello")
```

结果 浏览器控制台打印如下
![image](https://user-images.githubusercontent.com/29992802/143689573-be6ea3d5-325c-44b5-b332-aadaf58d176b.png)

希望得到你的帮助.....thanks

**Comment by wf0** [comment]
你好啊，我先确认以下，你的项目是vue2还是vue3 ？再者，你的服务区收到你的连接了吗？

**Comment by wf0** [comment]
你好啊，我复现了你的问题：
![image](https://user-images.githubusercontent.com/71718029/143731121-08a28e51-1632-4778-8887-b2e1853a7023.png)

----

Vue.use(ElementUI,
  new VueSocketIO({
    debug: false, // debug调试，生产建议关闭
    connection: "http://localhost:3000",
    vuex: {
      store,
      actionPrefix: 'SOCKET_',
      mutationPrefix: 'SOCKET_'
    },
    options: {     //Optional options, 
      autoConnect:false, //关闭自动连接，在用户登录后在连接。
    }
  })
);

是这样的，vue使用插件建议分开use，问题应该是你将你的vant跟socketIO放在一个use中去注册使用了。
你可以分开写：Vue.use(A).use(B),看看能不能使用socket进行通信。如果不行，再反馈，我再帮你看看~期待回复。

**Comment by OnZeng** [comment]
博主能加下我QQ嘛 qq:2528358258   救命
